// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolModel.Data;

#nullable disable

namespace SchoolModel.Data.Migrations
{
    [DbContext(typeof(Project584DbContext))]
    [Migration("20251202062434_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolModel.Data.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("availability");

                    b.Property<int>("CourseNumber")
                        .HasColumnType("int")
                        .HasColumnName("courseNumber");

                    b.Property<int>("Credits")
                        .HasColumnType("int")
                        .HasColumnName("credits");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("departmentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("courseName");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("CourseNumber", "DepartmentId")
                        .IsUnique();

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("deptCode")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("deptName");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("departmentId");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastName");

                    b.Property<bool>("PartTime")
                        .HasColumnType("bit")
                        .HasColumnName("partTime");

                    b.Property<string>("WorkloadStatus")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("workloadStatus");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Professor", (string)null);
                });

            modelBuilder.Entity("SchoolModel.Data.Models.ProfessorsCourses", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ProfessorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Professors_Courses", (string)null);
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Course", b =>
                {
                    b.HasOne("SchoolModel.Data.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Course_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Professor", b =>
                {
                    b.HasOne("SchoolModel.Data.Models.Department", "Department")
                        .WithMany("Professors")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Professor_Department");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SchoolModel.Data.Models.ProfessorsCourses", b =>
                {
                    b.HasOne("SchoolModel.Data.Models.Professor", "Course")
                        .WithMany("ProfessorsCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfessorsCourses_Course");

                    b.HasOne("SchoolModel.Data.Models.Course", "Professor")
                        .WithMany("ProfessorsCourses")
                        .HasForeignKey("ProfessorId")
                        .IsRequired()
                        .HasConstraintName("FK_ProfessorsCourses_Professor");

                    b.Navigation("Course");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Course", b =>
                {
                    b.Navigation("ProfessorsCourses");
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Professors");
                });

            modelBuilder.Entity("SchoolModel.Data.Models.Professor", b =>
                {
                    b.Navigation("ProfessorsCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
